#
@server = http://localhost:3000
# @server = http://175.45.194.10:3000
# @server = http://223.130.146.223:3000

### 회원가입 요청~
POST {{server}}/auth/user
Content-Type: application/json

{
    "email" : "master5@fancamp.com",
    "password": "1234",
    "chatName": "master5",
    "publicId": "master5",
    "profileImage": "",
    "isMaster": true
}


### 로그인 요청~
POST {{server}}/auth/user/signin
Content-Type: application/json

{
    "email" : "master4@fancamp.com",
    "password": "1234"
}


### 로그아웃 요청~
GET {{server}}/auth/user/signout