#
@server = http://localhost:3000
# @server = http://175.45.194.10:3000
# @server = http://223.130.146.223:3000

### 회원가입 요청~
POST {{server}}/camps
Content-Type: application/json

{
    "campName" : "camp2",
    "masterId": "5",
    "bannerImage": ""
}

###
GET {{server}}/camps/camp1

### 구독하기
POST {{server}}/camps/subscriptions/camp2
Content-Type: application/json

{
    "camperId" : "1",
    "masterId": "5"
}

### 모든 자신의 구독 가져오기
GET {{server}}/camps/subscriptions

###
GET {{server}}/camps/subscriptions/camp2
