#
@server = http://localhost:3000
# @server = http://175.45.194.10:3000
# @server = http://223.130.146.223:3000

### 회원가입 요청~
POST {{server}}/camps
Content-Type: application/json

{
    "campName" : "camp3",
    "masterId": "5",
    "bannerImage": "33"
}

###
GET {{server}}/camp/22

### 구독하기
POST {{server}}/camps/subscriptions/camp1
Content-Type: application/json

{
    "camperId" : "8",
    "masterId": "2"
}
