#
@server = http://localhost:3000
# @server = http://175.45.194.10:3000
# @server = http://223.130.146.223:3000

### 회원가입 요청~
POST {{server}}/camps
Content-Type: application/json

{
    "campName" : "camp1",
    "masterId": "2",
    "bannerImage": "33"
}

###
GET {{server}}/camp/22

