#
@server = http://localhost:3000
# @server = http://223.130.146.223:3000

### 포스트 id로 comment 생성하기
POST {{server}}/posts/comments
Content-Type: application/json

{
    "content": "hello33",
    "postId": 1
}

### 포스트 id로 코멘트 지우기
DELETE  {{server}}/posts/comments/1 


### 글 내용 수정
PATCH {{server}}/posts/comments/2
Content-Type: application/json

{
    "content" : "수정된 댓글2~~~~~~"
}
