#
@server = http://localhost:3000

### 유저 정보 수정(프로필 이미지, 채팅방이름)
PUT {{server}}/users
Content-Type: application/json

{
    "email" : "11@232",
    "password": "22",
    "username": "33",
    "profileImage": "44",
    "isMaster": true
}

###
GET {{server}}/users
