#
@server = http://localhost:3000
# @server = http://223.130.146.223:3000

### 회원가입 요청~
POST {{server}}/auth/user
Content-Type: application/json

{
    "email" : "11@2233",
    "password": "22",
    "username": "33",
    "profileImage": "44",
    "isMaster": true
}


### 로그인 요청~
POST {{server}}/auth/user/signin
Content-Type: application/json

{
    "email" : "11@22",
    "password": "string",
}


### 로그아웃 요청~
GET {{server}}/auth/user/signout